### ISSUE TITLE
DIRECTION HORIZONTALE ET VERTICALE

### ISSUE THREAD

**Issue by bipemn** [abarrau/jeedom-plugin-DaikinOnlineCtrl-doc#10]
Les clim Daikin FTXS50GV1B et FTXS35GV1B gèrent la direction verticale et horizontale du flux d'air.
Toutefois, à travers le plugin, elles sont inopérantes. Le module wifi est un BRP069B41 en version 1.2.48 et je n'ai donc pas fait la MaJ en 1.2.51 car le fonctionnement, hormis celui précité est correct. Une idée ?

**Comment by abarrau** [comment]
Bonjour, 
Le plugin s'appuie sur les spécifications du module wifi BRP069A41 (pour lequel uniquement arrêt et vertical sont disponibles), il se peut que votre module gère les directions autrement. 
1/ depuis votre appli daikin, vous me confirmez que ces fonctionnalités sont disponibles ? (photo de l'appli ?)
2/ Pourriez-vous m'envoyer le résultat des requêtes depuis l'onglet "test" de l'équipement. 

Merci,

**Comment by bipemn** [comment]
Bonjour, 
En retour, les réponses aux demandes : 
1/ Sur l'appli, la fonction direction est inexistante. Comme je l'ai indiqué, je n'ai pas mis à jour l'appli en 1.2.51 car il ne faudrait pas qu'il y ait par la suite des erreurs avec votre plugin. Est-ce que la MàJ comporterait la fonction direction ? 
2/ en pièce jointe. 
Merci 




----- Mail original -----

De: "abarrau" <notifications@github.com> 
À: "abarrau/jeedom-plugin-DaikinOnlineCtrl-doc" <jeedom-plugin-DaikinOnlineCtrl-doc@noreply.github.com> 
Cc: "bipemn" <bipemn.eric@laposte.net>, "Author" <author@noreply.github.com> 
Envoyé: Vendredi 22 Mars 2019 07:04:41 
Objet: Re: [abarrau/jeedom-plugin-DaikinOnlineCtrl-doc] DIRECTION HORIZONTALE ET VERTICALE (#10) 



Bonjour, 
Le plugin s'appuie sur les spécifications du module wifi BRP069A41 (pour lequel uniquement arrêt et vertical sont disponibles), il se peut que votre module gère les directions autrement. 
1/ depuis votre appli daikin, vous me confirmez que ces fonctionnalités sont disponibles ? (photo de l'appli ?) 
2/ Pourriez-vous m'envoyer le résultat des requêtes depuis l'onglet "test" de l'équipement. 

Merci,

**Comment by abarrau** [comment]
Bjr, 
Alors, 
1/ si sur l'appli, la fonction n'y ai pas alors cela signifie que ton module ne le permet pas. 
- exemple : moi j'ai un module BRP069A41 et je n'ai de dispo que le "arrêt" et "verticale", et dans l'appli on constate bien qu'il n'y a que ça de disponible. 
- le plugin propose des fonctionnalités ; car à un moment j'ai trouvé leur existence, mais cela ne veut pas dire que toutes les fonctions sont compatibles. 
- pour la mise à jour du module wifi, je ne saurais dire si cette version 1.2.51, car je n'ai pas le même module que toi et moi je suis en 3.3.6
2/ je ne vois pas de pj.

**Comment by bipemn** [comment]
Bsr, 
La P.j. est pourtant bien jointe ! 
Mais je la remets. C'est un pdf. 


----- Mail original -----

De: "abarrau" <notifications@github.com> 
À: "abarrau/jeedom-plugin-DaikinOnlineCtrl-doc" <jeedom-plugin-DaikinOnlineCtrl-doc@noreply.github.com> 
Cc: "bipemn" <bipemn.eric@laposte.net>, "Author" <author@noreply.github.com> 
Envoyé: Vendredi 22 Mars 2019 18:39:46 
Objet: Re: [abarrau/jeedom-plugin-DaikinOnlineCtrl-doc] DIRECTION HORIZONTALE ET VERTICALE (#10) 



Bjr, 
Alors, 
1/ si sur l'appli, la fonction n'y ai pas alors cela signifie que ton module ne le permet pas. 

    * exemple : moi j'ai un module BRP069A41 et je n'ai de dispo que le "arrêt" et "verticale", et dans l'appli on constate bien qu'il n'y a que ça de disponible. 
    * le plugin propose des fonctionnalités ; car à un moment j'ai trouvé leur existence, mais cela ne veut pas dire que toutes les fonctions sont compatibles. 
    * pour la mise à jour du module wifi, je ne saurais dire si cette version 1.2.51, car je n'ai pas le même module que toi et moi je suis en 3.3.6 2/ je ne vois pas de pj.

**Comment by abarrau** [comment]
Bjr, 
Désolé pour mes délais de réponse.
Je ne sais pas pourquoi, mais je ne reçois pas vos fichiers. pourriez-vous me l'envoyer directement sur hesky@hotmail.com. 
Merci

**Comment by abarrau** [comment]
Bonjour, 
Pouvez-vous me dire quelle est la situation sur ce ticket ? 
Merci, Cordialement, Aurélien

**Comment by bipemn** [comment]
Bonjour, 
Je ne m'en suis plus occupé car j'ai eu un soucis sur ma raspberry et je n'ai pas eu le temps de gérer cela. 
On va dire que l'on va clôturer ce ticket. Je verrai plus tard quand j'aurai plus de temps. 
Merci. 
Cordialement. 
ERic 

----- Mail original -----

De: "abarrau" <notifications@github.com> 
À: "abarrau/jeedom-plugin-DaikinOnlineCtrl-doc" <jeedom-plugin-DaikinOnlineCtrl-doc@noreply.github.com> 
Cc: "bipemn" <bipemn.eric@laposte.net>, "Author" <author@noreply.github.com> 
Envoyé: Mardi 22 Octobre 2019 11:18:35 
Objet: Re: [abarrau/jeedom-plugin-DaikinOnlineCtrl-doc] DIRECTION HORIZONTALE ET VERTICALE (#10) 



Bonjour, 
Pouvez-vous me dire quelle est la situation sur ce ticket ? 
Merci, Cordialement, Aurélien

**Comment by abarrau** [comment]
Ok, bon courage pour la remise en place de votre système. 
N'hésitez pas à revenir vers moi. 
Cdt, Aurélien
