### ISSUE TITLE
Interface Wifi Daikin BRP069B41

### ISSUE THREAD

**Issue by rvitch** [abarrau/jeedom-plugin-DaikinOnlineCtrl-doc#14]
Bonjour,
J'ai connecté l'Interface Wifi Daikin BRP069B41 sans probleme au plugin, il pilote bien la clim puisqu'il chauffe quand je lui demande du chaud et fait du froid quand je lui en demande  cependant aucune régulation ne se fait.
Voici le resultat du test avec le plugin (clim eteinte).
`[/common/basic_info] ret=OK,type=aircon,reg=eu,dst=1,ver=1_2_51,rev=D3A0C9F,pow=0,err=0,location=0,name=%43%6c%69%6d%20%43%6c%61%69%72%20%4d%61%74%69%6e,icon=3,method=home only,port=30050,id=,pw=,lpw_flag=0,adp_kind=3,pv=3.20,cpv=3,cpv_minor=20,led=1,en_setzone=1,mac=DCF50509302D,adp_mode=run,en_hol=0,grp_name=,en_grp=0

[/common/get_remote_method] ret=OK,method=home only,notice_ip_int=3600,notice_sync_int=60

[/common/get_notify] ret=OK,auto_off_flg=0,auto_off_tm=- -

[/aircon/get_price] ret=OK,price_int=27,price_dec=0

[/aircon/get_target] ret=OK,target=0

[/aircon/get_week_power] ret=OK,today_runtime=120,datas=0/0/0/100/0/100/0

[/aircon/get_year_power] ret=OK,previous_year=0/0/0/0/0/0/0/0/0/0/0/0,this_year=0/0/0/0/0/0/0/0/0/0

[/aircon/get_model_info] ret=OK,model=0000,type=N,pv=3.20,cpv=3,cpv_minor=20,mid=NA,humd=0,s_humd=0,acled=0,land=0,elec=1,temp=1,temp_rng=0,m_dtct=1,ac_dst=--,disp_dry=0,dmnd=1,en_scdltmr=1,en_frate=1,en_fdir=1,s_fdir=3,en_rtemp_a=0,en_spmode=7,en_ipw_sep=1,en_mompow=1,hmlmt_l=10.0

[/aircon/get_sensor_info] ret=OK,htemp=21.0,hhum=-,otemp=15.0,err=0,cmpfreq=0,mompow=1

[/aircon/get_control_info] ret=OK,pow=0,mode=4,adv=,stemp=21.0,shum=0,dt1=25.0,dt2=M,dt3=25.0,dt4=21.0,dt5=21.0,dt7=25.0,dh1=AUTO,dh2=50,dh3=0,dh4=0,dh5=0,dh7=AUTO,dhh=50,b_mode=4,b_stemp=21.0,b_shum=0,alert=255,f_rate=B,f_dir=3,b_f_rate=B,b_f_dir=3,dfr1=5,dfr2=5,dfr3=5,dfr4=B,dfr5=B,dfr6=5,dfr7=5,dfrh=5,dfd1=0,dfd2=0,dfd3=0,dfd4=3,dfd5=3,dfd6=0,dfd7=0,dfdh=0,dmnd_run=0,en_demand=0

[/aircon/get_monitordata (2.6.0)] ret=OK,mondata=pv=3.20,cpv=3,cpv_minor=20,mac=dcf50509302d,fan=303030,tap=42,mode=34,pow=30,rawrtmp=2b323035,humid=ff,trtmp=2b323630,fangl=2b313235,hetmp=2b333030,itelc=3030303030303032,eepid=30303030,cmpfrq=303030,otmp=2b313530,gx00=3530,gx01=3545,gx02=30303030,gx03=3030,gx04=3430,gx05=3030,gx06=30303030,gx07=30313930,gx08=00000000,gx09=46464646,gx0A=38314334,gx0B=3030,gx0C=3030,ResetCount=2,LastResetTime=2019/10/12 14:58:39,RouterDisconCnt=3,PollingErrCnt=0

[/common/get_regioncode (2.6.0)] ret=OK,reg=eu

[/common/get_servername (2.6.0)] ret=OK,ServerName=sha2.daikinonlinecontroller.com

[/common/get_datetime (2.6.0)] ret=OK,sta=2,cur=2019/10/13 9:55:52,reg=eu,dst=1,zone=282

[/common/get_wifi_setting (2.6.0)] ret=OK,ssid=private wifi ,security=mixed,key=%66%61%62%31%30%6f%70%72,link=1

[/common/get_network_setting (2.6.0)] ret=OK,auto_ip=1,auto_dns=1,ipaddr=,netmask=,gateway=,dns1=,dns2=,use_proxy=0,proxy=,proxy_port=0

[/common/get_wlanapch (2.6.0)] ret=OK,w_apch=10

[/aircon/get_demand_control (2.6.0)] ret=OK,type=1,en_demand=0,mode=0,max_pow=100,scdl_per_day=4,moc=0,tuc=0,wec=0,thc=0,frc=0,sac=0,suc=0

[/common/get_progsum (2.6.0)] ret=OK,csum=148eedb

[/aircon/get_scdltimer_info (2.6.0)] ret=OK,format=v1,f_detail=total#18;_en#1;_pow#1;_mode#1;_temp#4;_time#4;_vol#1;_dir#1;_humi#3;_spmd#2,scdl_num=3,scdl_per_day=6,en_scdltimer=0,active_no=1,scdl1_name=,scdl2_name=,scdl3_name=

[/common/get_group (2.6.0)] ret=OK,grp_name=,en_grp=0

[/common/get_wifi_scan_result (2.6.0)] ret=OK,cnt=0

[/aircon/get_year_power_ex (2.6.0)] ret=OK,curr_year_heat=0/0/0/0/0/0/0/0/0/34/0/0,prev_year_heat=0/0/0/0/0/0/0/0/0/0/0/0,curr_year_cool=0/0/0/0/0/0/0/0/0/0/0/0,prev_year_cool=0/0/0/0/0/0/0/0/0/0/0/0

[/aircon/get_month_power_ex (2.6.0)] ret=OK,curr_month_heat=0/0/0/0/0/3/0/0/1/0/0/19/11/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0,prev_month_heat=0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0,curr_month_cool=0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0,prev_month_cool=0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0

[/aircon/get_week_power_ex (2.6.0)] ret=OK,s_dayw=0,week_heat=11/19/0/0/1/0/0/3/0/0/0/0/0/0,week_cool=0/0/0/0/0/0/0/0/0/0/0/0/0/0

[/aircon/get_day_power_ex (2.6.0)] ret=OK,curr_day_heat=1/1/1/1/2/1/1/2/1/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0,prev_1day_heat=0/0/0/0/0/0/0/0/0/0/2/3/4/0/0/2/2/2/0/0/2/0/1/1,curr_day_cool=0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0,prev_1day_cool=0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0

[/common/get_holiday (2.6.0)] ret=OK,en_hol=0

[/aircon/get_demand_studyinfo (3.3.6)] ret=OK,c_rate=10,s_delay=15,c_count=4,u_temp=6`
Toute aide est la bienvenue

**Comment by abarrau** [comment]
Bonjour, 
Le plugin ne gère pas les régulations, il piloté uniquement, comme le fait l'application android.
Si votre clim ne s'arrête pas malgré une température élevée par rapport à la consigne, faut regarder côté clim. 
Cdt

**Comment by rvitch** [comment]
Bonjour et merci de m'avoir répondu.

Je n'ai pas du être assez clair, mais si j'utilise la télécommande ou
l'application daikin, la régulation se fait.
Le soucis est présent uniquement quand je la pilote via le plugin.

**Comment by abarrau** [comment]
Bonjour, 
(désolé pour ma réponse tardive). 

Comme je l'indique dans mon précédent message, le plugin envoie des requêtes au module Wifi comme le fait l'application Daikin. 
Le plugin n'a pas de notion de "régulation" (au même titre que la téléphone ou l'application), c'est la clim qui gère sa propre régulation. 

Je n'arrive donc pas à comprendre comment cela est possible et voir comment je peux vous aider. 
Lorsque vous dites que ça ne se régularise pas, cela signifie que si vous mettez 20° et qu'une fois les 20° attend, la clim continue de tourner ? combien de temps ? 
La même situation avec l'application, comment se comporte la clim ? 

Merci,

**Comment by rvitch** [comment]
Du coup après investigation poussé, j'ai un problème de régulation
global.ce n'est pas dû au plugin.
Il semble que j'ai trop de gaz et qu'il faille en enlever

Merci beaucoup de votre suivi.

**Comment by abarrau** [comment]
Ok bon courage
