### ISSUE TITLE
DaikinOnlineCtrl affiche class object no found au lancement du pluggin

### ISSUE THREAD

**Issue by coujma** [abarrau/jeedom-plugin-DaikinOnlineCtrl-doc#15]
Je viens d'installer sur un rasberry PI4B +rasbian buster et un jeedom 4.0.21 (le systeme boot sur le disque dur /def/sda2/)

Apres avoir installer et congigurer le pluggin DaikinOnlineCtrl j'obtient une page blanche avec un bandeau rouge
 "class object no found "

j'ai essayer de voir si il charge bien la class olindote et la j'obtient une page blanche sans rien de plus 

je suis sur chrome 

merci de m'aider si il y a moyen de faire fonctionner

**Comment by abarrau** [comment]
Bonjour, 
(désolé pour ma réponse tardive)

Je vais sortir une nouvelle version pour corriger ce problème. 
Toutefois, d'ici là, si vous souhaitez apporter une correction, vous pouvez aller modifier le fichier : 
/plugins/DaikinOnlineCtrl/desktop/php/DaikinOnlineCtrl.php

A la ligne 60, remplacer : 
> foreach (object::all() as $object) {

par 

> foreach (jeeObject::all() as $object) {

Je vous laisse valider ce point. 
Cordialement, Aurélien

**Comment by coujma** [comment]
Bonjour

Oui merci j’avais trouvé l’astuce sur le groupe facebook

 

J’ai oublié de complété ma demande de support 

Cordialement 

De : abarrau <notifications@github.com> 
Envoyé : mardi 22 octobre 2019 10:54
À : abarrau/jeedom-plugin-DaikinOnlineCtrl-doc <jeedom-plugin-DaikinOnlineCtrl-doc@noreply.github.com>
Cc : coujma <coujma@free.fr>; Author <author@noreply.github.com>
Objet : Re: [abarrau/jeedom-plugin-DaikinOnlineCtrl-doc] DaikinOnlineCtrl affiche class object no found au lancement du pluggin (#15)

 

Bonjour,
(désolé pour ma réponse tardive)

Je vais sortir une nouvelle version pour corriger ce problème.
Toutefois, d'ici là, si vous souhaitez apporter une correction, vous pouvez aller modifier le fichier :
/plugins/DaikinOnlineCtrl/desktop/php/DaikinOnlineCtrl.php

A la ligne 60, remplacer :

foreach (object::all() as $object) {

par

foreach (jeeObject::all() as $object) {

Je vous laisse valider ce point.
Cordialement, Aurélien
