### ISSUE TITLE
Dysfonctionnement remontée et pilotage du module

### ISSUE THREAD

**Issue by lansoftys** [abarrau/jeedom-plugin-DaikinOnlineCtrl-doc#3]
Bonjour, depuis la mise à jour du module ce matin et malgré avoir réinstallé le plugin, je ne peux ni piloter ma clim par le biais du plugin daikinonline jeedom ni avoir de retour d'information sur son état ou les sondes. Le message d'erreur affiché est "le plugin n'est plus accessible d'un point de vue réseau".

Merci par avance pour votre aide

Cordialement

Fabien

**Comment by abarrau** [comment]
Bonjour,
Il me faudrait des log et copie d'écran de votre config.
Il n'y a eu aucune mise à jour du plugin depuis 1an...
Quelle version de jeedom ?
Merci,
Aurélien

**Comment by lansoftys** [comment]
Bonsoir Abarrau, 

Merci pour votre retour, ci joint les copies écrans de ma config jeedom par contre lorsque je veux télécharger les logs du plugin daikin, il n'y en a plus...bizarre. Je tourne sur une plateforme RPI3 et sur jeedom V. 3.1.7. 
Je vous confirme qu'hier matin en ouvrant l'APK daikin sur mon android, j'ai été contraint de faire monter la dernière mise à jour du firmware du module wifi daikin car sinon je ne pouvais plus avoir accès aux fonctionnalités de la clim...Dans la journée, j'ai constaté sur jeedom avoir des messages d'erreur de communication du plugin et l'impossibilité de commander ma clim par celui-ci. Je pense que daikin a du modifier l'API..
Merci encore pour votre aide.
Bien cordialement
Fabien
![config1](https://user-images.githubusercontent.com/45242014/48920691-9fe8ab80-ee9a-11e8-857c-856698c26885.JPG)
![config2](https://user-images.githubusercontent.com/45242014/48920692-9fe8ab80-ee9a-11e8-9fa7-63584b3c1b66.JPG)
![config3](https://user-images.githubusercontent.com/45242014/48920693-9fe8ab80-ee9a-11e8-9902-d6ed13fe04f2.JPG)
![config4](https://user-images.githubusercontent.com/45242014/48920694-9fe8ab80-ee9a-11e8-82f9-eec0643a6156.JPG)
![version jeedom](https://user-images.githubusercontent.com/45242014/48920696-a0814200-ee9a-11e8-8691-1139cbe24e9e.JPG)

**Comment by abarrau** [comment]
Hello,

donc on parle d'une montée de version de l'APK daikin qui serait à
l'origine du problème c'est bien ça ?
Car coté jeedom, je n'ai pas mis à jour le plugin.

Merci pour ces informations importantes.

Au niveau de votre équipement, vous avez un onglet "test".
Pouvez-vous lancer le test et me remonter les valeurs des requêtes passées
?
(ou si vous pouvez le donner un accès restreint à votre système, sur la
partie "daikin" uniquement).

Merci d'avance,
Cdt,
Aurélien

**Comment by lansoftys** [comment]
Bonjour Aurélien, 

Effectivement il s'agit bien d'une mise à jour firmware du module wifi de la clim en lui-même, mise à jour poussée par l'APK daikin lors de son lancement...du coup j'ai lancé des test requêtes via le plugin daikin sur jeedom (voir ci joint en txt)
Bonne journée 
Fabien
[test plugin daikin.txt](https://github.com/abarrau/jeedom-plugin-DaikinOnlineCtrl-doc/files/2610652/test.plugin.daikin.txt)

**Comment by abarrau** [comment]
Bjr Fabien, 

Je n'utilise jamais l'APK Daikin, mais en effet, je viens de tester et j'ai eu besoin d'upgradé également l'APK (de 3.3.1 à 3.3.6).
Par contre, je n'ai aucun problème de fonctionnement avec Jeedom. 

En regardant la liste des requêtes que tu m'as envoyé, je constate que les requêtes principales ne sont plus disponibles de ton coté ... très étrange. 
- As-tu essayé de redémarrer électriquement le module ? 
- J'ai l'impression que utilise le cloud daikin, pourrais-tu essayer de "désinscrire" le module afin de n'avoir qu'une connexion locale ? 
Ne reproduisant pas le problème, je vais avoir du mal à debuger ... :(

Cdt,
Aurélien

**Comment by anyall** [comment]
Bonjour,

Même pb, depuis la MAJ des modules, je n'arrive plus à les faire fonctionner via Jeedom mais par contre çà marche toujours avec l'app sur mon Smartphone.

D'un point de vue réseau, j'arrive à pinger le module mais dans les log du plugin j'ai ce type de message :

[2018-12-09 14:36:04][INFO] : [EXEC|Clim Salon(39)|Redémarrer le module(548)] execute(): redémarrage du module
[2018-12-09 14:36:04][INFO] : [EXEC|Clim Salon(39)|Redémarrer le module(548)] execute(): redémarrage du module
[2018-12-09 14:36:04][WARNING] : [EXEC|Clim Salon(39)] sendDOCRequest(): ERROR: Le flux suivant n'est pas accéssible (error/timeout):http://192.168.60.40/common/reboot
[2018-12-09 14:36:04][WARNING] : [EXEC|Clim Salon(39)] sendDOCRequest(): ERROR: Le flux suivant n'est pas accéssible (error/timeout):http://192.168.60.40/common/reboot
[2018-12-09 14:36:04][WARNING] : [EXEC|Clim Salon(39)|Redémarrer le module(548)] execute(): ERROR: La requête de redémarrage n'a pas put être réalisée
[2018-12-09 14:36:04][WARNING] : [EXEC|Clim Salon(39)|Redémarrer le module(548)] execute(): ERROR: La requête de redémarrage n'a pas put être réalisée
[2018-12-09 14:37:03][WARNING] : [CRON|Clim Salon(39)] sendDOCRequest(): ERROR: Le flux suivant n'est pas accéssible (error/timeout):http://192.168.60.40/common/basic_info
[2018-12-09 14:37:03][WARNING] : [CRON|Clim Salon(39)] ERROR: Le module n'est pas accessible d'un point de vue réseau
[2018-12-09 14:38:03][WARNING] : [CRON|Clim Salon(39)] sendDOCRequest(): ERROR: Le flux suivant n'est pas accéssible (error/timeout):http://192.168.60.40/common/basic_info
[2018-12-09 14:38:03][WARNING] : [CRON|Clim Salon(39)] ERROR: Le module n'est pas accessible d'un point de vue réseau
[2018-12-09 14:39:02][WARNING] : [CRON|Clim Salon(39)] sendDOCRequest(): ERROR: Le flux suivant n'est pas accéssible (error/timeout):http://192.168.60.40/common/basic_info

Quand j'essaie d'aller sur l'URL (basic_info), j'obtiens les infos suivantes :

ret=OK,type=aircon,reg=eu,dst=1,ver=1_2_51,rev=D3A0C9F,pow=0,err=0,location=0,name=%44%61%69%6b%69%6e%41%50%36%39%39%33%37,icon=0,method=home only,port=30050,id=,pw=,lpw_flag=0,adp_kind=3,pv=3.20,cpv=3,cpv_minor=20,led=1,en_setzone=1,mac=409F386E077E,adp_mode=run,en_hol=0,grp_name=,en_grp=0

Enfin dans l'onglet Infos du plugin, le nom apparait mais pas les autres infos comme la version, l'adresse MAC etc...

1x sur 100 ça finit par marcher mais qu'une seule fois et j'obtiens alors la version et l'adresse MAC mais toujours pas les autres infos...

**Comment by abarrau** [comment]
Bonjour, 

Merci pour ce retour complémentaire. 
Malheureusement, je ne rencontre pas ce problème malgré une mise à jour de l'APK également. 

Même question : 
- As-tu essayé de redémarrer électriquement le module ?
- Utilises-tu le cloud daikin ? 

Merci,

**Comment by abarrau** [comment]
Bonjour Anyall, 
qu'en est-il de ton coté sur ce problème ? 
Merci,
Aurélien

**Comment by lansoftys** [comment]
Bonjour à tous,
Je reprends le fil de la discussion et vous retourne mes derniers essais. On parle de l'APK daikin, mais honnêtement elle n'est pas en cause, elle a juste déclenchée chez moi une mise à jour du module wifi brp pour une version actuelle 1.2.51
Le problème vient de cette mise à jour directement car j'ai profité d'une nouvelle installation de clim pour installer deux nouveaux modules wifi et le problème est identique... "Le module n'est pas accessible d'un point de vue réseau".
Concrètement il s'agit pourtant d'une nouvelle installation sans inscription sur le cloud daikin juste en local.. 
Il faudrait plutôt contacter les développeurs de daikin pou

**Comment by abarrau** [comment]
Bjr, 
qu'en est-il de votre coté ? 
cdt, Aurélien

**Comment by lansoftys** [comment]
Bonjour Aurélien, depuis la dernière mise à jour du plugin daikin sur jeedom, c'est impeccable tout refonctionne comme avant ainsi que les deux derniers modules wifi installés. Merci encore pour cette mise à jour.
Cordialement 
Fabien
