### ISSUE TITLE
[DaikinOnlineCtrl] Info sur type de clim utilisant le plugin

### ISSUE THREAD

**Issue by bipemn** [abarrau/jeedom-plugin-DaikinOnlineCtrl-doc#7]

**Comment by bipemn** [comment]
Bonjour,
Je fais donc remonté que la clim Daikin FTXS50GV1B et FTXS35GV1B fonctionnent avec ce plugin
Seul problème, les directions verticale et horizontale sont inopérantes. Le module wifi est un BRP069B41 en version 1.2.48 et je n'ai donc pas fait la MaJ en 1.2.51

**Comment by abarrau** [comment]
Bjr 
Merci pour ce retour. 
Si les direction n'apparaissent pas dans l'appli Android, les fonctions ne pourront pas être disponible via le plugin. 
Je ferme, au besoin réouvrir :)
